#ifndef SPKDTREESPLITMETHOD_H_
#define SPKDTREESPLITMETHOD_H_

typedef enum sp_kdtree_split_method_t {
	SP_KDTREE_RANDOM,
	SP_KDTREE_MAX_SPREAD,
	SP_KDTREE_INCREMENTAL
} SP_KDTREE_SPLIT_METHOD;

#endif /* SPKDTREESPLITMETHOD_H_ */
